### ISSUE TITLE
try out flow launcher as powertoys alternative

### ISSUE THREAD

**Issue by tho-myr** [m1chaelwilliams/make-windows-pretty#3]
https://www.flowlauncher.com/

it's way more customizabl, has community made plugins, custom themes, a bunch of extra settings like cutom hotkeys, is open source and runs on w10&w11. way better than powertoys in my opinion and especially for devs a must have

**Comment by vimichael** [comment]
I ended up trying it out and I love it! Thanks for the suggestion. I'll get around to updating this repo to reflect that shortly.
